import { Inter } from "next/font/google";
//import "./globals.css";
import Footer from "../component/footer.js";
import 'bootstrap/dist/css/bootstrap.css'

import Dashboard from "../component/dashboard.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Dashboard/>
        {children}
        <Footer />
        

      </body>
    </html>
  );
}
